name: "CLA"
on:
  issues:
    types: [opened, closed]
  

jobs:
  CLA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: "TEST ACTION"
    #  if: github.event.action == 'opened' || github.event.action == 'edited'
      uses: ibakshay/action-template@dev
      with: 
        mytoken: ${{ secrets.GITHUB_TOKEN }}
