name: "Issue Created"
on:
  pull_request:

jobs:
  CLA_CHECK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: "TEST ACTION"
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
      uses: ibakshay/action-template@dev-release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        pathtocla: 'cla.json'
        branch: 'master'
